# Generated by Django 5.2 on 2025-04-18 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_apikey_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API-ключ', 'verbose_name_plural': 'API-ключи'},
        ),
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AddField(
            model_name='bot',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма выделенного депозита для торговли', max_digits=15, null=True, verbose_name='Депозит'),
        ),
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='bot',
            name='trading_pair',
            field=models.CharField(blank=True, help_text='Например, BTC/USDT', max_length=50, null=True, verbose_name='Торговая пара'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='API-ключ'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_secret',
            field=models.CharField(max_length=255, verbose_name='Секретный ключ'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='exchange',
            field=models.CharField(choices=[('bybit', 'Bybit'), ('binance', 'Binance'), ('okx', 'OKX')], max_length=20, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bot',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='bots.apikey', verbose_name='Привязанный API-ключ'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название бота'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='strategy',
            field=models.CharField(choices=[('spot', 'Spot Trading'), ('futures', 'Futures Trading')], max_length=50, verbose_name='Стратегия'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
