# Generated by Django 5.2 on 2025-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_apikey_options_alter_bot_options_bot_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(max_length=1024, verbose_name='API-ключ'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_secret',
            field=models.CharField(max_length=1024, verbose_name='Секретный ключ'),
        ),
    ]
