# Generated by Django 5.2 on 2025-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_apikey_api_key_alter_apikey_api_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название бота'),
        ),
    ]
