# Generated by Django 5.2 on 2025-04-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_bot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='additional_settings',
            field=models.JSONField(blank=True, help_text='Дополнительные параметры бота (например, stop_loss, take_profit)', null=True, verbose_name='Дополнительные настройки'),
        ),
        migrations.AddField(
            model_name='bot',
            name='leverage',
            field=models.IntegerField(blank=True, help_text='Кредитное плечо, используемое ботом', null=True, verbose_name='Кредитное плечо'),
        ),
        migrations.AddField(
            model_name='bot',
            name='margin_type',
            field=models.CharField(blank=True, choices=[('isolated', 'Isolated'), ('cross', 'Cross')], max_length=20, null=True, verbose_name='Тип маржи'),
        ),
        migrations.AddField(
            model_name='bot',
            name='trade_mode',
            field=models.CharField(blank=True, help_text='Например, order_grid или trend_following', max_length=50, null=True, verbose_name='Режим торговли'),
        ),
    ]
