# Generated by Django 5.2 on 2025-04-28 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_bot_additional_settings_bot_leverage_bot_margin_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма выделенного депозита для торговли', max_digits=15, verbose_name='Депозит'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='leverage',
            field=models.IntegerField(default=1, help_text='Кредитное плечо, используемое ботом', verbose_name='Кредитное плечо'),
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('user', 'name')},
        ),
    ]
