# Generated by Django 5.2 on 2025-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_bot_deposit_alter_bot_leverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='Запущен ли бот'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='additional_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры бота', null=True, verbose_name='Дополнительные настройки'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='stopped', max_length=20, verbose_name='Статус'),
        ),
    ]
