# Generated by Django 5.2 on 2025-05-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_bot_is_running_alter_bot_additional_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='algorithm',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=20, verbose_name='Алгоритм'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='leverage',
            field=models.IntegerField(blank=True, default=1, help_text='Кредитное плечо, используемое ботом', null=True, verbose_name='Кредитное плечо'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='trade_mode',
            field=models.CharField(blank=True, choices=[('order_grid', 'Order Grid'), ('martingale', 'Martingale'), ('custom', 'Custom')], help_text='Например, order_grid или martingale', max_length=50, null=True, verbose_name='Режим торговли'),
        ),
    ]
