# Generated by Django 5.2 on 2025-05-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_bot_algorithm_alter_bot_leverage_and_more'),
    ]

    operations = [
    ]
