# Generated by Django 5.2 on 2025-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_auto_20250505_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название бота'),
        ),
    ]
