# Generated by Django 5.2 on 2025-05-05 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_alter_bot_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Общая прибыль')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Количество сделок')),
                ('roi', models.FloatField(default=0.0, verbose_name='ROI (%)')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_summaries', to='bots.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Сводка по боту',
                'verbose_name_plural': 'Сводки по ботам',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('details', models.TextField(verbose_name='Подробности')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время события')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('financial_result', models.JSONField(blank=True, null=True, verbose_name='Финансовые результаты')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bots.bot', verbose_name='Бот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='bots_logent_user_id_c13c45_idx'), models.Index(fields=['bot', 'timestamp'], name='bots_logent_bot_id_5117f5_idx')],
            },
        ),
    ]
