# Generated by Django 5.2 on 2025-05-19 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_botperformancesummary_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('price', 'Цена'), ('base_volume', 'Объём базовой'), ('nominal_volume', 'Объём номинальной'), ('rsi', 'RSI'), ('cci', 'CCI'), ('mfi', 'MFI')], max_length=20, verbose_name='Тип сигнала')),
                ('signal_params', models.JSONField(default=dict, help_text="Например, {'period': 14, 'threshold': 30} для RSI", verbose_name='Параметры сигнала')),
                ('signal_interval', models.CharField(help_text="Например, '1h' для часового интервала", max_length=20, verbose_name='Интервал сигнала')),
                ('take_profit', models.FloatField(verbose_name='Тейк-профит (%)')),
                ('grid_overlap', models.FloatField(verbose_name='Перекрытие сетки (%)')),
                ('grid_orders', models.IntegerField(verbose_name='Количество ордеров в сетке')),
                ('martingale', models.FloatField(verbose_name='Коэффициент мартингейла (%)')),
                ('grid_spacing', models.FloatField(verbose_name='Отступ между ордерами (%)')),
                ('logarithmic_distribution', models.BooleanField(default=False, verbose_name='Логарифмическое распределение цен')),
                ('partial_grid', models.BooleanField(default=False, verbose_name='Частичное выставление сетки')),
                ('grid_follow', models.BooleanField(default=False, verbose_name='Подтяжка сетки')),
                ('stop_after_deals', models.BooleanField(default=False, verbose_name='Остановить бота после завершения сделок')),
                ('preset', models.CharField(blank=True, choices=[('conservative', 'Консервативный'), ('moderate', 'Умеренный'), ('aggressive', 'Агрессивный')], max_length=20, null=True, verbose_name='Предустановка')),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='bots.bot', verbose_name='Бот')),
            ],
        ),
    ]
