# Generated by Django 5.2 on 2025-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_botsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='deals_completed',
            field=models.IntegerField(default=0, help_text='Количество завершенных сделок ботом', verbose_name='Завершенные сделки'),
        ),
    ]
