# Generated by Django 5.2 on 2025-05-24 08:10

import bots.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_bot_deals_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(default=0, verbose_name='Текущая позиция')),
                ('avg_price', models.FloatField(default=0, verbose_name='Средняя цена покупки')),
                ('sell_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID ордера на продажу')),
                ('buy_orders', models.JSONField(default=list, verbose_name='Ордера на покупку')),
            ],
            options={
                'verbose_name': 'Позиция бота',
                'verbose_name_plural': 'Позиции ботов',
            },
        ),
        migrations.AddField(
            model_name='apikey',
            name='encryption_version',
            field=models.CharField(default='v1', max_length=10, verbose_name='Версия шифрования'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='trade_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сделки'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='additional_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры бота', null=True, validators=[bots.models.validate_additional_settings], verbose_name='Дополнительные настройки'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='leverage',
            field=models.IntegerField(blank=True, default=1, help_text='Кредитное плечо, используемое ботом', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Кредитное плечо'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='grid_orders',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ордеров в сетке'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='grid_overlap',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Перекрытие сетки (%)'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='grid_spacing',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Отступ между ордерами (%)'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='martingale',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Коэффициент мартингейла (%)'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='take_profit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Тейк-профит (%)'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['user', 'status'], name='bots_bot_user_id_89cfbd_idx'),
        ),
        migrations.AddField(
            model_name='botposition',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='bots.bot', verbose_name='Бот'),
        ),
    ]
