# Generated by Django 5.2 on 2025-05-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_botposition_apikey_encryption_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botposition',
            name='position_opened',
            field=models.BooleanField(default=False, verbose_name='Позиция открыта'),
        ),
    ]
