# Generated by Django 5.2 on 2025-05-24 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_botposition_position_opened'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'exchange'], name='bots_apikey_user_id_b8e396_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['trading_pair'], name='bots_bot_trading_fad40c_idx'),
        ),
    ]
