# Generated by Django 5.2 on 2025-05-25 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0017_alter_apikey_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='stop_loss',
            field=models.FloatField(blank=True, help_text='Уровень убытков в процентах, при котором позиция закрывается', null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Стоп-лосс (%)'),
        ),
    ]
