# Generated by Django 5.2 on 2025-05-25 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0018_botsettings_stop_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='botposition',
            name='highest_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная цена'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='combined_signals',
            field=models.JSONField(blank=True, default=list, help_text="Список сигналов для комбинации, например: [{'type': 'rsi', 'threshold': 30}, {'type': 'macd', 'condition': 'crossover'}]", verbose_name='Комбинация сигналов'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='combined_strategies',
            field=models.JSONField(blank=True, default=list, help_text="Список стратегий для комбинации, например: ['order_grid', 'trailing_stop']", verbose_name='Комбинация стратегий'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='dca_interval',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал DCA (минуты)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='trailing_stop_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Процент Trailing Stop (%)'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='trade_mode',
            field=models.CharField(blank=True, choices=[('order_grid', 'Order Grid'), ('martingale', 'Martingale'), ('custom', 'Custom'), ('dca', 'Dollar-Cost Averaging'), ('trailing_stop', 'Trailing Stop'), ('arbitrage', 'Arbitrage')], help_text='Например, order_grid или martingale', max_length=50, null=True, verbose_name='Режим торговли'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='signal_type',
            field=models.CharField(choices=[('price', 'Цена'), ('base_volume', 'Объём базовой'), ('nominal_volume', 'Объём номинальной'), ('rsi', 'RSI'), ('cci', 'CCI'), ('mfi', 'MFI'), ('macd', 'MACD'), ('bollinger_bands', 'Bollinger Bands'), ('stochastic', 'Stochastic'), ('volume_spike', 'Volume Spike'), ('ma_crossover', 'Moving Average Crossover'), ('pivot_points', 'Pivot Points')], max_length=20, verbose_name='Тип сигнала'),
        ),
    ]
