# Generated by Django 5.2 on 2025-05-25 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0020_bot_test_mode_alter_bot_additional_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='passphrase',
            field=models.CharField(blank=True, help_text='Требуется только для OKX', max_length=1024, null=True, verbose_name='Пароль API (для OKX)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='arbitrage_spread_threshold',
            field=models.FloatField(blank=True, default=0.5, help_text='Минимальный спред между спотом и фьючерсами для арбитражной сделки', null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Порог спреда для арбитража (%)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='ma_crossover_type',
            field=models.CharField(choices=[('sma', 'Простая (SMA)'), ('ema', 'Экспоненциальная (EMA)')], default='sma', max_length=20, verbose_name='Тип скользящей средней'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='pivot_points_period',
            field=models.CharField(choices=[('1h', '1 час'), ('4h', '4 часа'), ('D', 'День'), ('W', 'Неделя'), ('M', 'Месяц')], default='D', help_text="Например, 'D' для дневного периода, 'W' для недельного", max_length=20, verbose_name='Период для Pivot Points'),
        ),
    ]
