# Generated by Django 5.2.1 on 2025-06-02 15:34

import bots.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0021_apikey_passphrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='task_interval',
            field=models.IntegerField(default=60, help_text='Как часто проверять сигнал (в минутах)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал выполнения задачи (минуты)'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='combined_signals',
            field=models.JSONField(blank=True, default=list, help_text="Список сигналов, например: [{'type': 'rsi', 'threshold': 30}, {'type': 'macd', 'condition': 'crossover'}]", validators=[bots.models.validate_signal_params], verbose_name='Комбинация сигналов'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='signal_interval',
            field=models.CharField(choices=[('1m', '1 минута'), ('5m', '5 минут'), ('15m', '15 минут'), ('1h', '1 час'), ('4h', '4 часа'), ('1d', '1 день')], default='1h', help_text="Например, '1h' для часового интервала", max_length=20, verbose_name='Интервал свечей для сигнала'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='signal_params',
            field=models.JSONField(default=dict, help_text="Например, {'period': 14, 'threshold': 30} для RSI", validators=[bots.models.validate_signal_params], verbose_name='Параметры сигнала'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='signal_type',
            field=models.CharField(choices=[('price', 'Цена'), ('base_volume', 'Объём базовой'), ('nominal_volume', 'Объём номинальной'), ('rsi', 'RSI'), ('cci', 'CCI'), ('mfi', 'MFI'), ('macd', 'MACD'), ('bollinger_bands', 'Bollinger Bands'), ('stochastic', 'Stochastic'), ('volume_spike', 'Volume Spike'), ('ma_crossover', 'Moving Average Crossover'), ('pivot_points', 'Pivot Points'), ('adx', 'ADX'), ('atr', 'ATR'), ('ichimoku', 'Ichimoku')], default='price', max_length=20, verbose_name='Тип сигнала'),
        ),
    ]
